### ISSUE TITLE
Euler Max and Euler SMEA Dy Negative cannot be used in v-prediction models

### ISSUE THREAD

**Issue by yuanyixiangxin** [MisterChief95/sd-forge-extra-samplers#3]
These two samplers produce a lot of noise when in use
<img width="1225" alt="屏幕截图 2024-12-01 090959" src="https://github.com/user-attachments/assets/4f73c25e-9c5c-4722-b8b9-c6a3d9928919">

**Comment by yuanyixiangxin** [comment]
I've tried a lot and these two samplers don't work. All other samplers can work on the V-prediction model. Please fix them if you can, thank you very much

**Comment by MisterChief95** [comment]
I've noticed V-Pred models are more sensitive to the sampler/scheduler combo than EPS models are. Euler SMEA Dy Negative is already pretty touchy as is. Looking at your screenshot, I think when Scheduler type is `Automatic` it uses the `Uniform` sampler. I ran a couple XYZ grids to compare schedulers and as you can see, some work, some don't. That's just unfortunately how it is. Pick the one that looks the best and use that one. Additionally, you can consider grabbing this extension:
https://github.com/DenOfEquity/webUI_ExtraSchedulers

That extension is where the last 5 schedulers come from in the XYZ grid. It also adds some CFG++ samplers you can try and see if they work better.

![02324-3105604902](https://github.com/user-attachments/assets/ac34abbc-bf9e-436b-bd95-da8d7d4a4b32)
![02325-3105604902](https://github.com/user-attachments/assets/5e6d1a57-7894-43ba-a17e-008dd1679ef6)
![02326-3105604902](https://github.com/user-attachments/assets/17c14228-4633-4615-b228-4c5735baa246)
![02327-3105604902](https://github.com/user-attachments/assets/50e5374b-5d62-46a8-883d-4a7e2b4a2791)

Same story for Euler Max. The same samplers that look best from these ^^ work well here too:
![02328-3105604902](https://github.com/user-attachments/assets/fde0c6ad-48d8-4dfb-b4a9-f9f465e2e1b1)
